spring:
  application.name: ch3-scheduler-jpa
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
#      timeout: 1800
      tracking-modes: cookie

  forward-headers-strategy: framework
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel.enabled: true
  port: 8080

logging.config: classpath:config/logback-spring.xml

log:
  level: debug